### DISCUSSION TITLE
Resource Limits

### DISCUSSION THREAD

**Discussion by mlongarai** [CrowdStrike/falcon-helm#146] [General]
Hello 👋

I was searching through the official documentation and did not find any official resource limit parameterization for the agents.
Is there something I need to consider or can I just use the suggestion described in the values.yaml?

````
  resources:
     limits:
       cpu: 100m
       memory: 128Mi
    requests:
      cpu: 10m
      memory: 20Mi
````
Link: https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/falcon-sensor/values.yaml#L142

Thank you in advance!
