### ISSUE TITLE
falcon-sensor deployed as daemonset fails at init-container because permissions and missing 'touch' command

### ISSUE THREAD

**Issue by GiuseppeChiesa-TomTom** [CrowdStrike/falcon-helm#129]
We observed that while using the DaemonSet deployment type and the pod are not starting. 

from the helm template:
https://github.com/CrowdStrike/falcon-helm/blob/1c652a53ba6069402614980fc44529e008ae079c/helm-charts/falcon-sensor/templates/daemonset.yaml#L90

it seems the init-container tries to pre-provision the folders but: 

- it does not have security profile to allow creation of folder on hostPath and fails with error:
```bash
mkdir: cannot create directory '/opt/CrowdStrike': Permission denied
```
- the referenced container image does not contain the `touch` command, so even if the `securityContext` privileged is properly configured (by patching the template) the init-container still fails with
```bash
/bin/bash: touch: command not found
```

I think the init container should be based on simple `busybox` and include the correct security context. 
Can you confirm this, or I'm missing some configuration? 

The configuration we pass to the chart(ver. falcon-sensor-1.17.0 with K8S ver.1.22) is the following:

```yaml
falcon:
  cid: ******
node:
  image:
    pullSecrets: <our custom pullsecret>
    repository: <our custom registry>
    tag: 6.37.0-2001
```
