### ISSUE TITLE
Support for using existing Secret for pulling image from Private Registry

### ISSUE THREAD

**Issue by iamhoges** [CrowdStrike/falcon-helm#132]
I am trying to play around with `values.yaml` file in the `image.pullSecrets` section to be able to use an existing kubernetes secret in the cluster. 

I ended up updating the manifest file to get the secret name from the values.yaml file, for example:
```
      imagePullSecrets:
      {{- if .Values.container.image.pullSecrets }}
        - name: {{ .Values.container.image.pullSecrets.name }}
      {{- end }}
```
values.yaml:
```
image:
    repository: my-private-registry/crowdstrike/falcon-sensor
    pullPolicy: IfNotPresent
    pullSecrets:
      name: my-private-registry-creds
```
