### ISSUE TITLE
Feature: Add option to limit the Container Sensor to Fargate Pods

### ISSUE THREAD

**Issue by CrisNevares** [CrowdStrike/falcon-helm#134]
Currently, if an Amazon EKS Cluster contains both worker nodes and Fargate nodes/pods, the only way to achieve full coverage of the cluster using the falcon-sensor is to inject the Container Sensor as a sidecar to all pods.

Instead, we would like to be able to deploy both the node sensor and the container sensor as part of the same helm installation. This can be achieved by limiting the container sensor to those Fargate pods by adding a toleration to the falcon-sensor-injector Deployment spec. For example:

```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: eks.amazonaws.com/compute-type
                operator: In
                values:
                - fargate
```
