### ISSUE TITLE
[Docs] "Privileged" PSS is not required for Falcon Sensor sidecar configuration

### ISSUE THREAD

**Issue by lomluca** [CrowdStrike/falcon-helm#180]
In the Falcon Sensor README the following is stated:

https://github.com/CrowdStrike/falcon-helm/blob/ffb2b8cb66512e802591292ae1514da81abb924d/helm-charts/falcon-sensor/README.md?plain=1#L80-L86

However, I think this is required only for `node.enabled` to `true`. Indeed, in this configuration, the DeamonSet needs to be created with the following configuration:

https://github.com/CrowdStrike/falcon-helm/blob/ffb2b8cb66512e802591292ae1514da81abb924d/helm-charts/falcon-sensor/templates/daemonset.yaml#L118-L122

When the Helm Chart is deployed in sidecar mode, the creation of DeamonSet is skipped, obviously. Then, I cannot find any security context configuration in the codebase that requires privileged mode. For this type of deployment, I think the "baseline" level is enough. I tested it in EKS 1.25 and everything works fine.

**Comment by redhatrises** [comment]
Baseline doesn't allow SYS_PTRACE which is required for the container sensor; hence, the requirement for privileged.

**Comment by lomluca** [comment]
I'm sorry, but it's still not clear to me. This is the injected piece for the sidecar:
```
 name: crowdstrike-falcon-container
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 20Mi
    securityContext:
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
```

The sensor is running as root, isn't it enough to ptrace? 

Exposing **all namespaces pods** to privileged permissions just for the sake of security monitoring seems counter-intuitive to me, maybe I'm missing something.
