### ISSUE TITLE
no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"

### ISSUE THREAD

**Issue by papanito** [CrowdStrike/falcon-helm#206]
I get the following error while I try to install falcon in Kubernetes

```
unable to build kubernetes objects from current release manifest: resource mapping not found for name: "falcon-sensor-node" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1" ensure CRDs are installed first
```

Kubernetes version:  v1.25.9
Helm-Chart version:  1.20.2

Helm Values
```yaml
node:
  enabled: true
  daemonset:
    annotations: {}
    labels: {}
    tolerations:
      - operator: Exists
    updateStrategy: RollingUpdate

  image:
    repository: crowdstrike/falcon-sensor-centos7
    pullPolicy: Always
    pullSecrets: null
    tag: 6.25.0-12207

  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  terminationGracePeriod: 10

container:
  enabled: false
  disableNSInjection: false
  disablePodInjection: false
  certExpiration: 3650
  injectorPort: 4433
  domainName:

  image:
    repository: falcon-sensor
    pullPolicy: Always
    pullSecrets:
      enable: false
    tag: "latest"
```

Apparently psp should not be installed https://github.com/CrowdStrike/falcon-helm/blob/a767961573a7589ff12c8fc8e88957799b15b765/helm-charts/falcon-sensor/templates/node_psp.yaml

```
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
{{- if lt (int (semver .Capabilities.KubeVersion.Version).Minor) 25 }}
{{- if .Values.node.enabled }}
```
