### ISSUE TITLE
[falcon-sensor] Resources for falcon-sensor are not well generated

### ISSUE THREAD

**Issue by mcinquin** [CrowdStrike/falcon-helm#237]
Hello,

We can add resources section in falcon-sensot daemonset if we have configured backend in bpf.
Unfortunately, the manifest is improperly generated and the resources are not applied.

values.yaml
```yaml
node:
  # When enabled, Helm chart deploys the Falcon Sensors to Kubernetes nodes
  enabled: true

  # Overrides the backend leveraged by the Falcon Sensor (kernel, bpf)
  backend: bpf

  # Enable for use on Google's GKE Autopilot clusters
  gke:
    autopilot: false

  daemonset:
...
    # Resource settings that can be set with backend is set to bpf only. Cannot be used when backend is set to kernel.
    # This will be ignored if backend is set to kernel. Purposefully. The defaults are set to the minimum requirements.
    # Depending on the size of your cluster and the node types, you may need to increase these values.
    resources:
      limits:
        cpu: 250m
        ephemeral-storage: 100Mi
        memory: 500Mi
      requests:
        cpu: 250m
        ephemeral-storage: 100Mi
        memory: 500Mi
...
```

If we generate the files with the helm command:
```
helm template falcon-helm crowdstrike/falcon-sensor -f values.yaml
```

The field `resources` is missing, so the manifest is invalid
```yaml
# Source: falcon-sensor/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falcon-sensor
  labels:
    app: "falcon-sensor"
    app.kubernetes.io/name: falcon-sensor
    app.kubernetes.io/instance: falcon-helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "kernel_sensor"
    crowdstrike.com/provider: crowdstrike
    helm.sh/chart: falcon-sensor-1.23.1
  namespace: falcon-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: falcon-sensor
      app.kubernetes.io/instance: falcon-helm
      app.kubernetes.io/component: "kernel_sensor"
      crowdstrike.com/provider: crowdstrike
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sensor.falcon-system.crowdstrike.com/injection: disabled
      labels:
        app: "falcon-sensor"
        app.kubernetes.io/name: falcon-sensor
        app.kubernetes.io/instance: falcon-helm
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: "kernel_sensor"
        crowdstrike.com/provider: crowdstrike
        helm.sh/chart: falcon-sensor-1.23.1
    spec:
      imagePullSecrets:
        - name: falcon-sensor-pull-secret
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
      initContainers:
      # This init container creates empty falconstore file so that when
      # it's mounted into the sensor-node-container, k8s would just use it
      # rather than creating a directory.  Mounting falconstore file as
      # a file volume ensures that AID is preserved across container
      # restarts.  Sensor versions 6.54+ have a helper binary to initialize falconstore.
      - name: init-falconstore
        image: "registry.crowdstrike.com/falcon-sensor/eu-1/release/falcon-sensor:7.05.0-16004-1.falcon-linux.x86_64.Release.EU-1"
        imagePullPolicy: "Always"
        command:
          - /bin/bash
        args: ['-c', 'if [ -x "/opt/CrowdStrike/falcon-daemonset-init" ]; then echo "Running falcon-daemonset-init -i" ; /opt/CrowdStrike/falcon-daemonset-init -i ; else if [ -d "/host_opt/CrowdStrike/falconstore" ] ; then echo "Re-creating /opt/CrowdStrike/falconstore as it is a directory instead of a file"; rm -rf /host_opt/CrowdStrike/falconstore; fi; mkdir -p /host_opt/CrowdStrike && touch /host_opt/CrowdStrike/falconstore; fi']
        volumeMounts:
          - name: falconstore-dir
            mountPath: /host_opt
        resources:
          requests:
            cpu: 10m
            ephemeral-storage: 100Mi
            memory: 50Mi
          limits:
            cpu: 10m
            ephemeral-storage: 100Mi
            memory: 50Mi
        securityContext:
          runAsUser: 0
          privileged: true
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
      containers:
      - name: falcon-node-sensor
        image: "registry.crowdstrike.com/falcon-sensor/eu-1/release/falcon-sensor:7.05.0-16004-1.falcon-linux.x86_64.Release.EU-1"
        imagePullPolicy: "Always"
        # Various pod security context settings. Bear in mind that many of these have an impact
        # on the Falcon Sensor working correctly.
        #
        # - User that the container will execute as. Typically necessary to run as root (0).
        # - Runs the Falcon Sensor containers as privileged containers. This is required when
        #   running the Falcon Linux Sensor on Kubernetes nodes to properly run in the node's
        #   kernel and to actually protect the node.
        securityContext:
          runAsUser: 0
          privileged: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
        limits:
          cpu: 250m
          ephemeral-storage: 100Mi
          memory: 500Mi
        requests:
          cpu: 250m
          ephemeral-storage: 100Mi
          memory: 500Mi**
        envFrom:
        - configMapRef:
            name: falcon-sensor-config
        volumeMounts:
          - name: falconstore
            mountPath: /opt/CrowdStrike/falconstore
      volumes:
        - name: falconstore-dir
          hostPath:
            path: /opt
            type: DirectoryOrCreate
        - name: falconstore
          hostPath:
            path: /opt/CrowdStrike/falconstore
      serviceAccountName: crowdstrike-falcon-sa
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      hostPID: true
      hostIPC: true
```

Regards
