### ISSUE TITLE
Deployment on GCP Kubernetes fails

### ISSUE THREAD

**Issue by ongyo-sensei** [CrowdStrike/falcon-helm#277]
Hello,

We are deploying sensor to GCP Kubernetes (not autopilot) and we are getting following error:

`init-falconstore mkdir: cannot create directory '/host_opt/CrowdStrike': Read-only file system`

It looks like template is hard coded for that path here:
https://github.com/CrowdStrike/falcon-helm/blob/2aa1642fbe2269ce4eb00073035078b0212d1b83/helm-charts/falcon-sensor/templates/daemonset.yaml#L109

And for GCP from their documentation root folder is read only.
There are other directories that are writable:
https://cloud.google.com/container-optimized-os/docs/concepts/disks-and-filesystem

Could you please help us or add some value or workaround this issue? 
We want to deploy sensor on GCP GKE cluster.

@alvicsam

**Comment by redhatrises** [comment]
Are you enabling eBPF and using sensor version 7.10.0?

**Comment by alvicsam** [comment]
Yes, bpf option is enabled in values.yaml, we use latest version of sensor and chart

**Comment by redhatrises** [comment]
I am unable to reproduce this. Running the following config works fine with GKE + GCOS:

```
falcon:
  cid: mycid
node:
  enabled: true
  backend: bpf
  image:
    tag: 7.10.0-16303-1.falcon-linux.x86_64.Release.US-1
    ...
```
