### ISSUE TITLE
AKS - Scheduling on system node pool

### ISSUE THREAD

**Issue by ibm-bersch** [CrowdStrike/falcon-helm#302]
It is best practice for AKS setups to use the `CriticalAddonsOnly=true:NoSchedule` taint to prevent application pods from being scheduled on system node pools. See [System and user node pools](https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli#system-and-user-node-pools)

Therefore I would suggest to update [documentation](https://github.com/CrowdStrike/falcon-helm/tree/main/helm-charts/falcon-sensor) to specify following in values.yaml when deploying the falcon sensor to AKS and `CriticalAddonsOnly` taint on system node pool:
```yaml
node:
  # ...
  daemonset:
    # ...
    tolerations:
      # ...
      # Allow schedule on system node pools
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
```

And/or add it commented out to the [values.yaml](https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/falcon-sensor/values.yaml)
