### ISSUE TITLE
Ways to reference existing value for clusterName in helm-charts/cs-k8s-protection-agent

### ISSUE THREAD

**Issue by gniltaws** [CrowdStrike/falcon-helm#311]
Our clusters are managed by gitops/Argo CD.  We have a global variable for the cluster's shortname `.Values.global.clusterName` which I'd like to be able to use, instead of needing a separate Values.yaml for each cluster.

I've worked out a few ways of doing it, in separate branches in my fork:  (I'm pretty inexperienced with Github.com, so apologies if this is a confusing way to link them)
1. [Default to using `Values.global.clusterName`](https://github.com/CrowdStrike/falcon-helm/compare/main...gniltaws:falcon-helm:default-clustername) 
This uses my chosen variable, which might not be what others would want to use.

```yaml
# templates/configmap.yaml
AGENT_CLUSTER_NAME: {{ (.Values.crowdstrikeConfig.clusterName | default .Values.global.clusterName) | quote }}
```

2. [Use user-defined variable for clusterName](https://github.com/CrowdStrike/falcon-helm/compare/main...gniltaws:falcon-helm:clusterNameOverrideTemplate)

This lets the user define a template (which can reference another variable)

```yaml
#  Values.yaml
crowdstrikeConfig:
  clusterName: ""
  clusterNameOverrideTemplate: "{{ .Values.global.clusterName }}"

global:
  clusterName: myClusterName
```

```yaml
# templates/configmap.yaml
{{- if .Values.crowdstrikeConfig.clusterNameOverrideTemplate }}
  AGENT_CLUSTER_NAME: {{ tpl .Values.crowdstrikeConfig.clusterNameOverrideTemplate . | quote }}
{{- else }}
  AGENT_CLUSTER_NAME: {{ .Values.crowdstrikeConfig.clusterName | quote }}
{{- end }}
```

3. [Use already-existing configmap instead of creating it](https://github.com/CrowdStrike/falcon-helm/compare/main...gniltaws:falcon-helm:support-existing-resources)

This adds a new variable in Values.yaml `.Values.crowdstrikeConfig.existingConfigMap`.  When defined, `configmap.yaml` is not created and `existingConfigMap` is used in the deployment's `envFrom`:

```yaml
# templates/deployment.yaml
          envFrom:
            - configMapRef:
                {{- if .Values.crowdstrikeConfig.existingConfigMap }}
                name: {{ .Values.crowdstrikeConfig.existingConfigMap }}
                {{- else }}
                name: {{ include "cs-k8s-protection-agent.fullname" . }}
                {{- end }}
```

I'd be happy to make any changes needed, but I will need help with the `values.schema.json` validation.

**Comment by r3motecontrol** [comment]
We solved this easily using [helm parameters](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-parameters). You can leave the `clusterName` blank in `values.yaml`, and in the ApplicationSet, set the helm parameter (i.e., clusterName)

```
source:
  helm:
    parameters:
    - name: crowdstrikeConfig.clusterName
      value: "{{.name}}"  # if using a Cluster Generator, it is automatically available.
```

[Argo Cluster Generator](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster/)
