### ISSUE TITLE
Daemonset doesn't force a rollout when the CID changes

### ISSUE THREAD

**Issue by ben-nelson-nbcuni** [CrowdStrike/falcon-helm#318]
When the `FALCONCTL_OPT_CID` value changes in the Configmap, the Daemonset pods do not restart. This is a common issue for helm charts. Helm has a [tips and tricks section](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) dedicated to this issue.

On your pod annotations in [daemonset.yaml](https://github.com/CrowdStrike/falcon-helm/blob/7937483629dc2ed8b2d3a35cc43e1393b5ae0ae2/helm-charts/falcon-sensor/templates/daemonset.yaml#L41) please add the following to force a pod restart on CID changes:
```
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```
