### ISSUE TITLE
Tags aren't being set with falcon-sensor

### ISSUE THREAD

**Issue by olobrian** [CrowdStrike/falcon-helm#320]
# Expected

When setting `falcon.tags` in `values.yaml`, tags should be set on the sensor so I can filter/search for specific hosts in the UI

# Actual

Nothing happens. There aren't any references to `.Values.falcon.tags` that I can see in the helm chart.

**Comment by redhatrises** [comment]
Can you provide an example of the changes you are making in addition to the CLI commands (if you are using CLI that is) that you using? Generally, values.yaml changes should be made via CLI, in a single manifest file, or via a custom values.yaml that is external to the helm chart.

**Comment by r3motecontrol** [comment]
> There aren't any references to .Values.falcon.tags that I can see in the helm chart

It's not explicitly referenced, but they are definitely being picked up from the values.yaml file 
[configmap](https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/falcon-sensor/templates/configmap.yaml#L16-L20)

You could also test this using `helm template`

An e.g. `values.yaml`

```
  falcon:
    cid: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-01
    apd:
    aph:
    app:
    trace: none
    feature:
    message_log:
    billing:
    tags: test
    provisioning_token:
```

`helm template . -f values.yaml` should produce this output
```
---
# Source: crowdstrike-falcon/charts/falcon-sensor/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-falcon-sensor-config
  namespace: default
  labels:
    app: "falcon-sensor"
    app.kubernetes.io/name: falcon-sensor
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "container_sensor"
    crowdstrike.com/provider: crowdstrike
    helm.sh/chart: falcon-sensor-1.29.1
data:
  FALCONCTL_OPT_CID: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-01
  FALCONCTL_OPT_TAGS: "test"
  FALCONCTL_OPT_TRACE: "none"
  FALCONCTL_OPT_BACKEND: "bpf"
---
```
