### ISSUE TITLE
Ability to read sensitive data (cid) from k8s secret

### ISSUE THREAD

**Issue by poonsalai** [CrowdStrike/falcon-helm#326]
Hi Team

Seems right now the helm chart for falcon-sensor is accepting the falcon-cid only via helm chart values.yaml.
But as that is treated as a sensitive value, it would be great to have an option in chart where user can pass a k8s secret and the cid value can be read from there, with that way there will be no need to put the secret in helm or checked in repo as well.

https://github.com/CrowdStrike/falcon-helm/tree/falcon-sensor-1.28.1/helm-charts/falcon-sensor

`FALCONCTL_OPT_CID: {{ .Values.falcon.cid }}`

Could you please suggest if this can be taken on priority and worked upon.

Thanks
Sharad

**Comment by nmohoric** [comment]
They've closed multiple pull requests related to this and their reasoning makes no sense.  Good luck.

https://github.com/CrowdStrike/falcon-helm/pull/273#issuecomment-2023072790

**Comment by Jaykul** [comment]
You **can** set both of the secrets as secrets, it's just that their instructions are insecure, and the values.yaml is undocumented.

First set two secrets, one with **both** the client id and secret in the data:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: crowdstrike-agent-apiaccess
type: Opaque
data:
  AGENT_CLIENT_ID: xxxB64ENCxxxCLIENTxIDxxxx
  AGENT_CLIENT_SECRET: xxxB64ENCxxxCLIENTxSECRETxxxx
```

The other with the [appropriate pull secret](https://github.com/CrowdStrike/falcon-helm/blob/957e18c9bd79c0d5a4ff13d76828180a441c1e59/helm-charts/cs-k8s-protection-agent/templates/_helpers.tpl#L66). This has to be in [.docker/config.json](https://docs.docker.com/reference/cli/docker/#sample-configuration-file) format, and you need to use the one that's correct for your environment, and embed the dockerAPIToken they give you in the config.yaml you download.

```
apiVersion: v1
kind: Secret
metadata:
  name: crowdstrike-imagepullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: xxxB64ENCxxxDOCKERxCONFIGxJSONxxxx
```

Then, in your values.yaml you can set the [image.pullSecrets](https://github.com/CrowdStrike/falcon-helm/blob/957e18c9bd79c0d5a4ff13d76828180a441c1e59/helm-charts/cs-k8s-protection-agent/values.yaml#L11) **instead of** the `crowdstrikeConfig.dockerAPIToken` and the [`crowdstrikeConfig.existingSecret`](https://github.com/CrowdStrike/falcon-helm/blob/957e18c9bd79c0d5a4ff13d76828180a441c1e59/helm-charts/cs-k8s-protection-agent/values.yaml#L53) **instead of** the `crowdstrikeConfig.clientID` and `crowdstrikeConfig.clientSecret`:

```yaml
image:
  repository: registry.crowdstrike.com/kubernetes_protection/kpagent
  pullSecrets: crowdstrike-imagepullsecret
crowdstrikeConfig:
  existingSecret: crowdstrike-agent-apiaccess
  ...
```

Note that if you provide these, you must _not_ provide the `crowdstrikeConfig.

**Comment by hrbasic** [comment]
I had a similar issue with another Helm chart where the option to specify an existing secret wasn’t available. If you are using Kustomization for your deployment, this might help you, e.g.: 
`falcon-shra-executor-patch.yaml`
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: falcon-shra-executor
  namespace: crowdstrike-falcon-io-shra
spec:
  template:
    spec:
      containers:
        - name: executor
          env:
            - name: "CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  name: crowdstrike-config-secret
                  key: CLIENT_ID
            - name: "CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: crowdstrike-config-secret
                  key: CLIENT_SECRET
      initContainers:
        - name: executor-init
          env:
            - name: "CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  name: crowdstrike-config-secret
                  key: CLIENT_ID
            - name: "CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: crowdstrike-config-secret
                  key: CLIENT_SECRET
```
Kustomization: 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crowdstrike-falcon-io-shra
  namespace: crowdstrike-falcon-io-shra

resources: 
  - crowdstrike-registry-sealed-secret.yaml
  - crowdstrike-config-sealed-secret.yaml
  - falcon-shra-executor-role.yaml
  - falcon-shra-executor-role-binding.yaml

helmCharts:
  - name: falcon-self-hosted-registry-assessment
    repo: https://crowdstrike.github.io/falcon-helm
    releaseName: falcon-shra
    namespace: crowdstrike-falcon-io-shra
    valuesFile: values.yaml
    version: 1.3.0

patchesStrategicMerge:
  - delete-clusterrole-patch.yaml
  - delete-clusterrole-binding-patch.yaml
  - falcon-shra-executor-patch.yaml
```
