### ISSUE TITLE
Fix and document how to use existing secrets in cs-k8s-protection-agent

### ISSUE THREAD

**Issue by Jaykul** [CrowdStrike/falcon-helm#328]
Currently, the config.yaml you provide has the `crowdstrikeConfig.dockerAPIToken` directly in the yaml, and the instructions require us to put our clientApiKey there as well -- in any GitOps environment, this would result in putting secrets into source control.

Additionally, **the chart is currently wrong** [here](https://github.com/CrowdStrike/falcon-helm/blob/957e18c9bd79c0d5a4ff13d76828180a441c1e59/helm-charts/cs-k8s-protection-agent/templates/deployment.yaml#L31), so if I pre-create the and provide the `image.pullSecrets` it will generate invalid config (i.e. two `name:` entries).

Then you should document how to do it..

If you're using GitOps and need to commit your values.yaml, you **can** set the secrets ahead of time. There are two of them:

The client ApiAccess secret needs to have the `AGENT_CLIENT_ID` and `AGENT_CLIENT_SECRET` in it. Create this however you create your secrets:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: crowdstrike-agent-apiaccess
type: Opaque
data:
  AGENT_CLIENT_ID: xxxBASE64xENCODEDxxxCLIENTxIDxxxx
  AGENT_CLIENT_SECRET: xxxBASE64xENCODEDxxxCLIENTxSECRETxxxx
```

The other, with the [appropriate Image Pull Secret](https://github.com/CrowdStrike/falcon-helm/blob/957e18c9bd79c0d5a4ff13d76828180a441c1e59/helm-charts/cs-k8s-protection-agent/templates/_helpers.tpl#L66) needs to be a `kubernetes.io/dockerconfigjson` secret which is in [.docker/config.json](https://docs.docker.com/reference/cli/docker/#sample-configuration-file) format. You need to use the config that's correct for your environment, and embed the dockerAPIToken in it.

EXAMPLE JSON NEEDED HERE

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: crowdstrike-imagepullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: xxxBASE64xENCODEDxxxDOCKERxCONFIGxJSONxxxx
```

Then, in your values.yaml you can set the [image.pullSecrets](https://github.com/CrowdStrike/falcon-helm/blob/957e18c9bd79c0d5a4ff13d76828180a441c1e59/helm-charts/cs-k8s-protection-agent/values.yaml#L11) **instead of** the `crowdstrikeConfig.dockerAPIToken` and the [`crowdstrikeConfig.existingSecret`](https://github.com/CrowdStrike/falcon-helm/blob/957e18c9bd79c0d5a4ff13d76828180a441c1e59/helm-charts/cs-k8s-protection-agent/values.yaml#L53) **instead of** the `crowdstrikeConfig.clientID` and `crowdstrikeConfig.clientSecret`:

```yaml
image:
  repository: registry.crowdstrike.com/kubernetes_protection/kpagent
  pullSecrets: crowdstrike-imagepullsecret
crowdstrikeConfig:
  existingSecret: crowdstrike-agent-apiaccess
  ...
```
